#ifndef _DOLCESDK_PSP2_LIBHTTP_METHODS_H_
#define _DOLCESDK_PSP2_LIBHTTP_METHODS_H_

typedef enum {
	SCE_HTTP_METHOD_GET,
	SCE_HTTP_METHOD_POST,
	SCE_HTTP_METHOD_HEAD,
	SCE_HTTP_METHOD_OPTIONS,
	SCE_HTTP_METHOD_PUT,
	SCE_HTTP_METHOD_DELETE,
	SCE_HTTP_METHOD_TRACE,
	SCE_HTTP_METHOD_CONNECT
} SceHttpMethods;

#endif	/* _DOLCESDK_PSP2_LIBHTTP_METHODS_H_ */

