#ifndef _DOLCESDK_PSP2_LIBHTTP_STATUS_CODE_H_
#define _DOLCESDK_PSP2_LIBHTTP_STATUS_CODE_H_

/* Informational 1xx */
#define SCE_HTTP_STATUS_CODE_CONTINUE							100
#define SCE_HTTP_STATUS_CODE_SWITCHING_PROTOCOLS				101
#define SCE_HTTP_STATUS_CODE_PROCESSING							102

/* Successful 2xx */
#define SCE_HTTP_STATUS_CODE_OK									200
#define SCE_HTTP_STATUS_CODE_CREATED							201
#define SCE_HTTP_STATUS_CODE_ACCEPTED							202
#define SCE_HTTP_STATUS_CODE_NON_AUTHORITATIVE_INFORMATION		203
#define SCE_HTTP_STATUS_CODE_NO_CONTENT							204
#define SCE_HTTP_STATUS_CODE_RESET_CONTENT						205
#define SCE_HTTP_STATUS_CODE_PARTIAL_CONTENT					206
#define SCE_HTTP_STATUS_CODE_MULTI_STATUS						207

/* Redirection 3xx */
#define SCE_HTTP_STATUS_CODE_MULTIPLE_CHOICES					300
#define SCE_HTTP_STATUS_CODE_MOVED_PERMANENTRY					301
#define SCE_HTTP_STATUS_CODE_MOVED_PERMANENTLY					301
#define SCE_HTTP_STATUS_CODE_FOUND								302
#define SCE_HTTP_STATUS_CODE_SEE_OTHER							303
#define SCE_HTTP_STATUS_CODE_NOT_MODIFIED						304
#define SCE_HTTP_STATUS_CODE_USE_PROXY							305
#define SCE_HTTP_STATUS_CODE_TEMPORARY_REDIRECT					307

/* Client Error 4xx */
#define SCE_HTTP_STATUS_CODE_BAD_REQUEST						400
#define SCE_HTTP_STATUS_CODE_UNAUTHORIZED						401
#define SCE_HTTP_STATUS_CODE_PAYMENT_REQUIRED					402
#define SCE_HTTP_STATUS_CODE_FORBIDDDEN							403
#define SCE_HTTP_STATUS_CODE_NOT_FOUND							404
#define SCE_HTTP_STATUS_CODE_METHOD_NOT_ALLOWED					405
#define SCE_HTTP_STATUS_CODE_NOT_ACCEPTABLE						406
#define SCE_HTTP_STATUS_CODE_PROXY_AUTHENTICATION_REQUIRED		407
#define SCE_HTTP_STATUS_CODE_REQUEST_TIME_OUT					408
#define SCE_HTTP_STATUS_CODE_CONFLICT							409
#define SCE_HTTP_STATUS_CODE_GONE								410
#define SCE_HTTP_STATUS_CODE_LENGTH_REQUIRED					411
#define SCE_HTTP_STATUS_CODE_PRECONDITION_FAILED				412
#define SCE_HTTP_STATUS_CODE_REQUEST_ENTITY_TOO_LARGE			413
#define SCE_HTTP_STATUS_CODE_REQUEST_URI_TOO_LARGE				414
#define SCE_HTTP_STATUS_CODE_UNSUPPORTED_MEDIA_TYPE				415
#define SCE_HTTP_STATUS_CODE_REQUEST_RANGE_NOT_SATISFIBLE		416
#define SCE_HTTP_STATUS_CODE_EXPECTATION_FAILED					417
#define SCE_HTTP_STATUS_CODE_UNPROCESSABLE_ENTITY				422
#define SCE_HTTP_STATUS_CODE_LOCKED								423
#define SCE_HTTP_STATUS_CODE_FAILED_DEPENDENCY					424
#define SCE_HTTP_STATUS_CODE_UPGRADE_REQUIRED					426

/* Server Error 5xx */
#define SCE_HTTP_STATUS_CODE_INTERNAL_SERVER_ERROR				500
#define SCE_HTTP_STATUS_CODE_NOT_IMPLEMENTED					501
#define SCE_HTTP_STATUS_CODE_BAD_GATEWAY						502
#define SCE_HTTP_STATUS_CODE_SERVICE_UNAVAILABLE				503
#define SCE_HTTP_STATUS_CODE_GATEWAY_TIME_OUT					504
#define SCE_HTTP_STATUS_CODE_HTTP_VERSION_NOT_SUPPORTED			505
#define SCE_HTTP_STATUS_CODE_INSUFFICIENT_STORAGE				507

#endif	/* _DOLCESDK_PSP2_LIBHTTP_STATUS_CODE_H_ */

