#ifndef _DOLCESDK_PSP2_NET_NETCTL_H_
#define _DOLCESDK_PSP2_NET_NETCTL_H_

#pragma message "<psp2/net/netctl.h> is deprecated. Please include <psp2/libnetctl.h>."

#include <psp2/libnetctl.h>


/* This is for backward compatibility with Vitasdk */

#ifdef __cplusplus
extern "C" {
#endif

#define SCE_NETCTL_INFO_CONFIG_NAME_LEN_MAX 64
#define SCE_NETCTL_INFO_SSID_LEN_MAX        32

typedef enum SceNetCtlInfoType {
	SCE_NETCTL_INFO_GET_CNF_NAME = 1,
	SCE_NETCTL_INFO_GET_DEVICE,
	SCE_NETCTL_INFO_GET_ETHER_ADDR,
	SCE_NETCTL_INFO_GET_MTU,
	SCE_NETCTL_INFO_GET_LINK,
	SCE_NETCTL_INFO_GET_BSSID,
	SCE_NETCTL_INFO_GET_SSID,
	SCE_NETCTL_INFO_GET_WIFI_SECURITY,
	SCE_NETCTL_INFO_GET_RSSI_DBM,
	SCE_NETCTL_INFO_GET_RSSI_PERCENTAGE,
	SCE_NETCTL_INFO_GET_CHANNEL,
	SCE_NETCTL_INFO_GET_IP_CONFIG,
	SCE_NETCTL_INFO_GET_DHCP_HOSTNAME,
	SCE_NETCTL_INFO_GET_PPPOE_AUTH_NAME,
	SCE_NETCTL_INFO_GET_IP_ADDRESS,
	SCE_NETCTL_INFO_GET_NETMASK,
	SCE_NETCTL_INFO_GET_DEFAULT_ROUTE,
	SCE_NETCTL_INFO_GET_PRIMARY_DNS,
	SCE_NETCTL_INFO_GET_SECONDARY_DNS,
	SCE_NETCTL_INFO_GET_HTTP_PROXY_CONFIG,
	SCE_NETCTL_INFO_GET_HTTP_PROXY_SERVER,
	SCE_NETCTL_INFO_GET_HTTP_PROXY_PORT,
} SceNetCtlInfoType;

typedef enum SceNetCtlState {
	SCE_NETCTL_STATE_DISCONNECTED,
	SCE_NETCTL_STATE_CONNECTING,
	SCE_NETCTL_STATE_FINALIZING,
	SCE_NETCTL_STATE_CONNECTED
} SceNetCtlState;

#ifdef __cplusplus
}
#endif

#endif /* _DOLCESDK_PSP2_NET_NETCTL_H_ */

